"""
Main bridge orchestrator — wires SIP, RTP, and LiveKit together.

run_bridge() is the single entry point that:
  1. Acquires a port from the pool
  2. Connects to LiveKit and publishes the SIP audio track
  3. Sends a SIP INVITE to Exotel
  4. Monitors for hang-up signals (BYE, RTP silence, LiveKit disconnect)
  5. Cleans up everything on exit
"""

import asyncio
import json
import logging
import time
import uuid

from livekit import rtc
from livekit.api import AccessToken, VideoGrants, SIPGrants

from .config import (
    EXOTEL_MEDIA_IP,
    LK_API_KEY,
    LK_API_SECRET,
    LK_URL,
    NO_RTP_AFTER_ANSWER_SECONDS,
    RTP_SILENCE_TIMEOUT_SECONDS,
    validate_config,
)
from .inbound_listener import (
    register_call_id,
    unregister_call_id,
)
from .port_pool import get_port_pool
from .rtp_bridge import RTPMediaBridge
from .sip_client import ExotelSipClient
from src.core.logger import logger, setup_logging

setup_logging()


async def run_bridge(
    phone_number: str,
    room_name: str | None = None,
    sip_config: dict | None = None,
    result_queue=None,
    preallocated_port: int | None = None,
    call_id: str | None = None,
    inbound_bye_event=None,
):
    """
    result_queue       : multiprocessing.Queue — put() result dict when SIP resolves.
    preallocated_port  : port already acquired by parent process; skip pool.acquire/release.
    call_id            : pre-generated by parent; passed to ExotelSipClient so parent can
                         register the inbound BYE event before the subprocess starts.
    inbound_bye_event  : multiprocessing.Event from parent; skip register_call_id when set.
    """
    if not validate_config():
        return

    if not LK_URL or not LK_API_KEY or not LK_API_SECRET:
        logger.error("[BRIDGE] Missing LiveKit configuration")
        return

    if not room_name:
        room_name = f"sip-bridge-{phone_number}-{uuid.uuid4().hex[:6]}"

    sip_config = sip_config or {}
    caller_id = sip_config.get("exotel_number")
    sip_host = sip_config.get("sip_host")
    sip_port = sip_config.get("sip_port")
    sip_domain = sip_config.get("sip_domain")

    pool = get_port_pool()
    owns_port = preallocated_port is None
    port = preallocated_port if preallocated_port is not None else pool.acquire()
    logger.info(f"[BRIDGE] phone={phone_number} room={room_name} rtp_port={port}")

    rtp_bridge = None
    sip_client = None
    inbound_bye = None
    owns_inbound_bye = inbound_bye_event is None
    ended_by_remote_bye = False
    _result_sent = False
    room = rtc.Room()

    def _send_result(payload: dict):
        nonlocal _result_sent
        if result_queue is not None and not _result_sent:
            result_queue.put(payload)
            _result_sent = True

    try:
        rtp_bridge = RTPMediaBridge(public_ip=EXOTEL_MEDIA_IP, bind_port=port)

        sip_client_kwargs = {"callee": phone_number, "rtp_port": port}
        if caller_id:
            sip_client_kwargs["caller_id"] = caller_id
        if sip_host:
            sip_client_kwargs["sip_host"] = sip_host
        if sip_port:
            sip_client_kwargs["sip_port"] = int(sip_port)
        if sip_domain:
            sip_client_kwargs["from_domain"] = sip_domain
        if call_id:
            sip_client_kwargs["call_id"] = call_id

        sip_client = ExotelSipClient(**sip_client_kwargs)

        if inbound_bye_event is not None:
            inbound_bye = inbound_bye_event
        else:
            inbound_bye = register_call_id(sip_client.call_id)

        # Hold/resume detection via SIP re-INVITE
        async def _on_hold_change(is_hold: bool):
            event_name = "call_hold" if is_hold else "call_resume"
            try:
                await room.local_participant.publish_data(
                    json.dumps({"event": event_name}).encode(),
                    topic="sip_bridge_events",
                )
                logger.info(f"[BRIDGE] Published {event_name}")
            except Exception as e:
                logger.error(f"[BRIDGE] Failed to publish {event_name}: {e}")

        sip_client.on_hold_change = lambda h: asyncio.create_task(_on_hold_change(h))

        # Tracks arriving before SIP 200 OK are queued; those arriving after are
        # wired directly.  This prevents pre-answer agent audio from being
        # buffered and dumped on pickup.
        pending_tracks: list = []
        sip_answered = False

        @room.on("track_subscribed")
        def on_track(track, publication, participant):
            if track.kind == rtc.TrackKind.KIND_AUDIO:
                if sip_answered:
                    logger.info(
                        f"[BRIDGE] Audio track from {participant.identity} "
                        f"(source={publication.source}) — adding to mixer"
                    )
                    rtp_bridge.add_outbound_track(track)
                    rtp_bridge.start_outbound_mixer()
                else:
                    logger.info(
                        f"[BRIDGE] Audio track from {participant.identity} "
                        f"(source={publication.source}) — queued (SIP not yet answered)"
                    )
                    pending_tracks.append(track)

        token = (
            AccessToken(LK_API_KEY, LK_API_SECRET)
            .with_identity(f"sip-{phone_number}")
            .with_metadata(json.dumps({"source": "exotel_bridge"}))
            .with_grants(VideoGrants(room_join=True, room=room_name))
            .with_sip_grants(SIPGrants(admin=True, call=True))
            .to_jwt()
        )
        await asyncio.wait_for(room.connect(LK_URL, token), timeout=15.0)
        logger.info(f"[BRIDGE] LiveKit connected: {room_name}")
        await rtp_bridge.start_inbound(room)

        await sip_client.connect()
        res = await sip_client.send_invite()
        if not res:
            logger.error("[BRIDGE] SIP failed")
            _send_result({
                "success": False,
                "call_status": sip_client.last_call_status or "failed",
                "sip_status_code": sip_client.last_sip_status_code,
                "sip_status_text": sip_client.last_sip_status_reason,
                "error": sip_client.last_sip_error or "SIP INVITE failed",
            })
            return

        # Signal the API that the call is established; bridge loop continues below
        _send_result({
            "success": True,
            "call_status": "answered",
            "room_name": room_name,
        })

        # Open RTP path; wire any tracks that arrived during ringing
        rtp_bridge.set_remote_endpoint(res["remote_ip"], res["remote_port"], res["pt"])
        sip_answered = True
        for track in pending_tracks:
            rtp_bridge.add_outbound_track(track)
        if pending_tracks:
            rtp_bridge.start_outbound_mixer()
            logger.info(f"[BRIDGE] Mixer started with {len(pending_tracks)} queued track(s)")

        answered_at = time.time()

        # Notify agent that call is answered
        try:
            await asyncio.sleep(0.5)
            await room.local_participant.publish_data(
                json.dumps({"event": "call_answered"}).encode(),
                topic="sip_bridge_events",
            )
            logger.info("[BRIDGE] Published call_answered event")
        except Exception as e:
            logger.error(f"[BRIDGE] Failed to publish call_answered event: {e}")

        disconnect_reason = "unknown"
        sip_mon = asyncio.create_task(sip_client.wait_for_disconnection())
        while True:
            # ── Signal 1: LiveKit room disconnected ──
            if room.connection_state != rtc.ConnectionState.CONN_CONNECTED:
                disconnect_reason = "livekit_disconnected"
                logger.info("[BRIDGE] LiveKit room disconnected")
                break

            # ── Signal 2: SIP BYE on outbound TCP (same connection as INVITE) ──
            if sip_mon.done():
                disconnect_reason = "sip_bye_outbound_tcp"
                ended_by_remote_bye = True
                logger.info("[BRIDGE] SIP BYE received on outbound TCP")
                break

            # ── Signal 3: SIP BYE on inbound TCP listener (new connection from Exotel) ──
            if inbound_bye and inbound_bye.is_set():
                disconnect_reason = "sip_bye_inbound_tcp"
                ended_by_remote_bye = True
                logger.info("[BRIDGE] SIP BYE received on inbound TCP listener")
                break

            since_rx = rtp_bridge.seconds_since_rx()

            # ── Signal 4: No RTP ever arrived after answer — call setup failure ──
            if (
                since_rx is None
                and NO_RTP_AFTER_ANSWER_SECONDS > 0
                and (time.time() - answered_at) > NO_RTP_AFTER_ANSWER_SECONDS
            ):
                disconnect_reason = "no_rtp_after_answer"
                logger.error(
                    "[RTP] No inbound RTP after %ss — call never connected, ending",
                    NO_RTP_AFTER_ANSWER_SECONDS,
                )
                break

            # ── Signal 5: RTP was flowing but stopped — caller hung up ──
            if (
                since_rx is not None
                and RTP_SILENCE_TIMEOUT_SECONDS > 0
                and since_rx > RTP_SILENCE_TIMEOUT_SECONDS
            ):
                disconnect_reason = "rtp_silence_after_flow"
                logger.info(
                    "[RTP] No audio for %.0fs (threshold=%ss) — caller hung up",
                    since_rx,
                    RTP_SILENCE_TIMEOUT_SECONDS,
                )
                break

            await asyncio.sleep(1)

        logger.info(f"[BRIDGE] Call ended — reason={disconnect_reason}")

    except Exception as e:
        logger.error(f"[BRIDGE] Error: {e}", exc_info=True)
        try:
            call_status = "failed"
            sip_status_code = None
            sip_status_text = str(e)
            if sip_client:
                call_status = sip_client.last_call_status or "failed"
                sip_status_code = sip_client.last_sip_status_code
                sip_status_text = sip_client.last_sip_status_reason or str(e)
            _send_result({
                "success": False,
                "call_status": call_status,
                "sip_status_code": sip_status_code,
                "sip_status_text": sip_status_text,
                "error": str(e),
            })
        except Exception:
            pass

    finally:
        if sip_client:
            if not ended_by_remote_bye:
                await sip_client.send_bye()
            await sip_client.close()

        if rtp_bridge:
            await rtp_bridge.close_streams()
            rtp_bridge.stop()

        await room.disconnect()

        # In subprocess path: owns_port and owns_inbound_bye are False —
        # the dispatcher monitor coroutine handles port release and call_id cleanup.
        # These branches only fire in standalone / test use.
        if owns_port:
            pool.release(port)
            logger.info(f"[BRIDGE] Port {port} released")

        if owns_inbound_bye and sip_client:
            unregister_call_id(sip_client.call_id)


def _bridge_subprocess_entry(
    phone_number: str,
    room_name: str,
    sip_config: dict,
    result_queue,
    preallocated_port: int,
    call_id: str,
    inbound_bye_event,
):
    """Top-level subprocess entry point — must be module-level to be picklable for spawn."""
    asyncio.run(run_bridge(
        phone_number=phone_number,
        room_name=room_name,
        sip_config=sip_config,
        result_queue=result_queue,
        preallocated_port=preallocated_port,
        call_id=call_id,
        inbound_bye_event=inbound_bye_event,
    ))
